apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-app
  template:
    metadata:
      labels:
        app: prom-app
    spec:
      containers:
        - name: prometheus-demo-container
          image: rudro25/my-custom-prometheus:latest
          ports:
            - containerPort: 8081
